[workspace]
members = [".", "entity"]

[workspace.dependencies]
log = "0.4"
dotenvy = "0.15"
anyhow = "1.0"
# thiserror = "1.0"

tokio = { version = "1.29", features = ["full"] }
arel = { version = "0.2.6" }

entity = { path = "./entity" }

# ================= end workspace =================
[package]
name = "homeland-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
# thiserror = { workspace = true }

tokio = { workspace = true }

arel = { workspace = true }
entity = { workspace = true }
