[package]
name = "homeland-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sqlx = { version = "0.7", features = [
  "runtime-tokio-rustls",
  "postgres",
  "macros",
] }

arel = { version = "0.2", features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
] }
